language: python

notifications:
  email: false

matrix:
  include:
    - os: linux
      env: INSTALL=yes
      python: 2.7

before_install:
    - if [ ${INSTALL} = "yes" ]; then
        sudo apt-get install xvfb ;
      fi

install:
    - if [ ${INSTALL} = "yes" ]; then
        pip install pexpect==4.2 ;
        pip install requests==2.9.1 ;
        pip install selenium==2.53.0 ;
        pip install lxml==3.3.3 ;
        pip install paramiko==1.16.0 ;
        pip install pysnmp==4.3.2 ;
        pip install pyvirtualdisplay==0.2.1 ;
        pip install sphinx ;
      fi

script:
    - ls ;
    - ./wf_tests/pylint_travis/doc.sh